build:
  resolveDependency: true
  chnageVersionNumber: true
  buildProject: true
  runUnitTests: true
  runSonarQubeTests: false
  packageCode: true
  uploadToRepository: true
  buildAsContainer: true
  runPostBuildActions: false

project:
  name: voting-worker
  builderVersion: "dotnet"
  version: "1.0.0"
  preferedRegistryIndex: 0
  buildCsprojPath: dotnet/Worker
  restoreCsprojPath: src/Worker

registry:
  - id: "dev-nexus"
    hostedRepository: "nuget-hosted"
    groupRepository: "nuget-group/index.json"
    hostToArtifact: true

buildArgs:
  - "/p:DeployOnBuild=true"
  - "/p:WebPublishMethod=FileSystem"
  - "/p:PackageAsSingleFile=true"
  - "/p:SkipInvalidConfigurations=true"
  - "/p:DesktopBuildPackageLocation='$(WORKSPACE)WebApp.zip'"
  - "/p:DeployIisAppPath='Default Web Site'"
  - "/p:Platform='Any CPU'"
  - "/p:Configuration=Release"

containerConfig:
  - name: voting-worker
    dockerFilePath: docker/Dockerfile
